### ISSUE TITLE
Hi, Not suport PHP 5.2

### ISSUE THREAD

**Issue by EOM** [cakebaker/controller-list-component#5]
Hi,
Not suport PHP 5.2, use function anonyme. only PHP 5.3 >=. Insert description in Readme.md

CakePHP 2.6<= Suport PHP 5.2>=
CakePHP 2.7>= Suport PHP 5.3>=

Parse error: syntax error, unexpected T_FUNCTION in /www/manjares_express/htdocs/dev/administracion/sys/app/Controller/Component/ControllerListComponent.php on line 32

**Comment by cakebaker** [comment]
Thanks for opening this ticket. I added a requirements notice to the readme.

However, if you are still using PHP 5.2, it's strongly recommended to upgrade to a newer PHP version. PHP 5.2 is outdated and reached its end of life more than five years ago (see http://php.net/eol.php).
